{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "748a35fa-3adc-49d8-895c-957bb073fcaa",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "from Banking.account import SavingsAccount, CurrentAccount\n",
    "from Banking.transaction import deposit, withdraw\n",
    "\n",
    "# Store accounts in session state\n",
    "if 'accounts' not in st.session_state:\n",
    "    st.session_state.accounts = {}\n",
    "if 'current_user' not in st.session_state:\n",
    "    st.session_state.current_user = None\n",
    "\n",
    "def create_account_ui():\n",
    "    st.subheader(\"Create New Account\")\n",
    "    name = st.text_input(\"Enter your name\")\n",
    "    acc_type = st.selectbox(\"Select account type\", [\"Savings\", \"Current\"])\n",
    "    initial_deposit = st.number_input(\"Initial deposit\", min_value=0.0)\n",
    "\n",
    "    if st.button(\"Create Account\"):\n",
    "        if acc_type == \"Savings\":\n",
    "            acc = SavingsAccount(name, initial_deposit)\n",
    "        else:\n",
    "            acc = CurrentAccount(name, initial_deposit)\n",
    "\n",
    "        st.session_state.accounts[acc.account_counter] = acc\n",
    "        st.success(f\"Account created successfully. Your account number is {acc.account_counter}\")\n",
    "\n",
    "def login_ui():\n",
    "    st.subheader(\"Login\")\n",
    "    acc_number = st.number_input(\"Enter your account number\", step=1, format=\"%d\")\n",
    "\n",
    "    if st.button(\"Login\"):\n",
    "        acc_number = int(acc_number)\n",
    "        if acc_number in st.session_state.accounts:\n",
    "            st.session_state.current_user = st.session_state.accounts[acc_number]\n",
    "            st.success(f\"Welcome, {st.session_state.current_user.name}!\")\n",
    "        else:\n",
    "            st.error(\"Invalid account number.\")\n",
    "\n",
    "def user_dashboard():\n",
    "    user = st.session_state.current_user\n",
    "    st.subheader(f\"Welcome, {user.name}\")\n",
    "    st.write(f\"Account Type: {'Savings' if isinstance(user, SavingsAccount) else 'Current'}\")\n",
    "    st.write(f\"Current Balance: ₹{user.get_balance():.2f}\")\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "    deposit_amount = st.number_input(\"Deposit Amount\", min_value=0.0, key=\"deposit\")\n",
    "    if st.button(\"Deposit\"):\n",
    "        deposit(user, deposit_amount)\n",
    "        st.success(f\"Deposited ₹{deposit_amount:.2f}\")\n",
    "\n",
    "    withdraw_amount = st.number_input(\"Withdraw Amount\", min_value=0.0, key=\"withdraw\")\n",
    "    if st.button(\"Withdraw\"):\n",
    "        if withdraw(user, withdraw_amount):\n",
    "            st.success(f\"Withdrawn ₹{withdraw_amount:.2f}\")\n",
    "        else:\n",
    "            st.error(\"Insufficient balance\")\n",
    "\n",
    "    if isinstance(user, SavingsAccount):\n",
    "        if st.button(\"Check Interest\"):\n",
    "            interest = user.calculate_interest()\n",
    "            st.info(f\"Interest earned: ₹{interest:.2f}\")\n",
    "\n",
    "    if st.button(\"Logout\"):\n",
    "        st.session_state.current_user = None\n",
    "        st.success(\"Logged out successfully.\")\n",
    "\n",
    "def main():\n",
    "    st.title(\"🏦 SIT Bank System\")\n",
    "    st.markdown(\"### Welcome to SIT Bank - Nagpur Branch\")\n",
    "\n",
    "    if st.session_state.current_user:\n",
    "        user_dashboard()\n",
    "    else:\n",
    "        tab1, tab2 = st.tabs([\"🔐 Login\", \"📝 Create Account\"])\n",
    "        with tab1:\n",
    "            login_ui()\n",
    "        with tab2:\n",
    "            create_account_ui()\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
